collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

repository: "Polo2/test_jekyll"

# Workaround for GH Page, from
# https://github.com/jekyll/jekyll/issues/332#issuecomment-18952908
gh_page_url: "/test_jekyll"

# gh_page_url: "" # when run locally
